# Generated by Django 5.2.4 on 2025-09-15 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_verified', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('selfie', models.ImageField(blank=True, help_text='A selfie of the Wheeler taken at the business.', max_length=255, null=True, upload_to='mobility_mapper_business_portal/wheeler_selfies/')),
                ('approved', models.BooleanField(default=False, help_text='Has this verification been approved by an admin?')),
                ('additional_features', models.ManyToManyField(blank=True, related_name='additional_in_verifications', to='businesses.accessibilityfeature')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='businesses.business')),
                ('confirmed_features', models.ManyToManyField(related_name='confirmed_in_verifications', to='businesses.accessibilityfeature')),
                ('mobility_device', models.ForeignKey(blank=True, help_text='Type of wheeled mobility device used during verification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='accounts.mobilitydevice')),
                ('wheeler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('business', 'wheeler')},
            },
        ),
        migrations.CreateModel(
            name='WheelerVerificationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='mobility_mapper_business_portal/verification_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_photos', to='businesses.accessibilityfeature')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='verification.wheelerverification')),
            ],
        ),
        migrations.CreateModel(
            name='WheelerVerificationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='businesses.business')),
                ('wheeler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('business', 'wheeler')},
            },
        ),
    ]
