# Generated by Django 5.2.4 on 2025-09-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheelerverificationapplication',
            name='reviewed',
        ),
    ]
