# Generated by Django 5.2.4 on 2025-09-23 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('verification', '0002_remove_wheelerverificationapplication_reviewed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheelerverification',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='businesses.business'),
        ),
        migrations.AlterField(
            model_name='wheelerverification',
            name='wheeler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wheelerverificationapplication',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests', to='businesses.business'),
        ),
        migrations.AlterField(
            model_name='wheelerverificationapplication',
            name='wheeler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wheelerverificationphoto',
            name='verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='verification.wheelerverification'),
        ),
    ]
