# Generated by Django 5.2.4 on 2025-09-15 15:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('group_code', models.CharField(blank=True, help_text="Group code for category grouping (e.g. 'retail', 'food_drink')", max_length=30, null=True)),
                ('group_description', models.CharField(blank=True, help_text="Description of the group (e.g. 'Retail', 'Food & Drink')", max_length=200, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium')], default='free', max_length=20)),
                ('description', models.JSONField()),
                ('membership_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('verification_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('street_address1', models.CharField(blank=True, default='', max_length=80)),
                ('street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('town_or_city', models.CharField(blank=True, default='', max_length=40)),
                ('county', models.CharField(blank=True, max_length=80, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='mobility_mapper_business_portal/business_logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('opening_hours', models.TextField(blank=True, null=True)),
                ('public_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('public_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('services_offered', models.TextField(blank=True, null=True)),
                ('special_offers', models.TextField(blank=True, help_text='Special offers or discounts available for wheelers', null=True)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL', null=True)),
                ('x_twitter_url', models.URLField(blank=True, help_text='X profile URL', null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL', null=True)),
                ('wheeler_verification_requested', models.BooleanField(default=False)),
                ('verified_by_wheelers', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessibility_features', models.ManyToManyField(blank=True, related_name='businesses', to='businesses.accessibilityfeature')),
                ('business_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('categories', models.ManyToManyField(blank=True, related_name='businesses', to='businesses.category')),
                ('membership_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='businesses.membershiptier')),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
    ]
