# Generated by Django 5.2.4 on 2025-07-16 23:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('cafe', 'Café'), ('retail', 'Retail Store'), ('gym', 'Gym'), ('hotel', 'Hotel'), ('healthcare', 'Healthcare'), ('other', 'Other')], max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('address', models.CharField(max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('accessibility_features', models.JSONField(blank=True, default=list)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('supporter', 'Supporter'), ('featured', 'Featured'), ('partner', 'Premier Partner')], default='free', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
