# Generated by Django 5.2.4 on 2025-09-14 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheelerverificationphoto',
            name='verification',
        ),
        migrations.AlterUniqueTogether(
            name='wheelerverificationapplication',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wheelerverificationapplication',
            name='business',
        ),
        migrations.RemoveField(
            model_name='wheelerverificationapplication',
            name='wheeler',
        ),
        migrations.RemoveField(
            model_name='wheelerverificationphoto',
            name='feature',
        ),
        migrations.DeleteModel(
            name='WheelerVerification',
        ),
        migrations.DeleteModel(
            name='WheelerVerificationApplication',
        ),
        migrations.DeleteModel(
            name='WheelerVerificationPhoto',
        ),
    ]
