# Generated by Django 5.2.4 on 2025-08-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='mobility_mapper_business_portal/business_logos/'),
        ),
        migrations.AlterField(
            model_name='wheelerverificationphoto',
            name='image',
            field=models.ImageField(upload_to='mobility_mapper_business_portal/verification_photos/'),
        ),
    ]
