# Generated by Django 5.2.4 on 2025-09-08 20:07

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, error_messages={'invalid_image': 'The uploaded image appears corrupted or unreadable.'}, null=True, upload_to='mobility_mapper_business_portal/business_logos/', validators=[core.validators.validate_logo]),
        ),
    ]
