# Generated by Django 5.2.4 on 2025-07-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='is_verified',
            new_name='is_approved',
        ),
        migrations.AddField(
            model_name='business',
            name='verified_by_wheelers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='wheeler_verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
