# Generated by ChatGPT: add verification_price to PricingTier
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingtier',
            name='verification_price',
            field=models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True),
        ),
    ]
