# Generated by Django 5.2.4 on 2025-08-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_business_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='address',
        ),
        migrations.AddField(
            model_name='business',
            name='county',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='street_address1',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='business',
            name='street_address2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='town_or_city',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
