# Generated by Django 5.2.4 on 2025-09-09 21:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_business_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WheelerVerificationRequest',
            new_name='WheelerVerificationApplication',
        ),
    ]
