# Generated by Django 5.2.4 on 2025-09-02 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_add_verification_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium')], default='free', max_length=20)),
                ('description', models.JSONField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('verification_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('membership_stripe_price_id', models.CharField(blank=True, max_length=100)),
                ('verification_stripe_price_id', models.CharField(blank=True, help_text='Stripe Price ID used for Wheeler verification purchases for this tier.', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='business',
            name='pricing_tier',
        ),
        migrations.AddField(
            model_name='business',
            name='membership_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='businesses.membershiptier'),
        ),
    ]
