# Generated by Django 5.2.4 on 2025-09-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_remove_wheelerverificationphoto_verification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='mobility_mapper_business_portal/business_logos/'),
        ),
    ]
