# Generated by Django 5.2.4 on 2025-07-18 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_rename_is_verified_business_is_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='wheeler_verification_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WheelerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_verified', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='businesses.business')),
                ('wheeler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('business', 'wheeler')},
            },
        ),
    ]
