# Generated by Django 5.2.4 on 2025-09-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_membershiptier_remove_business_pricing_tier_and_more'),
        ('checkout', '0002_purchase_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingTier',
        ),
    ]
