# Generated by Django 5.2.4 on 2025-07-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_wheeler_verification_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('supporter', 'Supporter'), ('featured', 'Featured')], default='free', max_length=20),
        ),
    ]
