# Generated by Django 5.2.4 on 2025-08-27 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_remove_business_address_business_county_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingtier',
            old_name='price_per_year',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='pricingtier',
            old_name='stripe_annual_price_id',
            new_name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='business',
            name='billing_frequency',
        ),
        migrations.RemoveField(
            model_name='pricingtier',
            name='price_per_month',
        ),
        migrations.RemoveField(
            model_name='pricingtier',
            name='stripe_monthly_price_id',
        ),
    ]
