# Generated by Django 5.2.4 on 2025-08-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_rename_price_per_year_pricingtier_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingtier',
            name='description',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='pricingtier',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pricingtier',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium')], default='free', max_length=20),
        ),
    ]
