# Generated by Django 5.2.4 on 2025-09-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_delete_pricingtier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershiptier',
            old_name='price',
            new_name='membership_price',
        ),
    ]
