# Generated by Django 5.2.4 on 2025-07-19 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_business'),
        ('businesses', '0004_alter_business_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
