# Generated by Django 5.2.4 on 2025-07-20 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_alter_business_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stripe_price_id', models.CharField(help_text='The Stripe Price ID for this tier', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='business',
            name='tier',
        ),
        migrations.AddField(
            model_name='business',
            name='pricing_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='businesses.pricingtier'),
        ),
    ]
