# Generated by Django 5.2.4 on 2025-08-28 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_agegroup_county_mobilitydevice_and_more'),
        ('businesses', '0005_alter_pricingtier_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheelerverification',
            name='mobility_device',
            field=models.ForeignKey(blank=True, help_text='Type of wheeled mobility device used during verification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='accounts.mobilitydevice'),
        ),
    ]
