# Generated by Django 5.2.4 on 2025-09-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_rename_price_membershiptier_membership_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiptier',
            name='membership_stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='membershiptier',
            name='verification_stripe_price_id',
        ),
    ]
