# Generated by Django 5.2.4 on 2025-08-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_alter_wheelerverification_mobility_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelerverification',
            name='selfie',
            field=models.ImageField(blank=True, help_text='A selfie of the Wheeler taken at the business.', null=True, upload_to='mobility_mapper_business_portal/wheeler_selfies/'),
        ),
    ]
