# Generated by Django 5.2.4 on 2025-07-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_pricingtier_remove_business_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingtier',
            name='price_per_year',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='pricingtier',
            name='stripe_annual_price_id',
            field=models.CharField(blank=True, help_text='The Stripe Price ID for yearly billing', max_length=100),
        ),
    ]
