# Generated by Django 5.2.4 on 2025-07-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_pricingtier_price_per_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='pricingtier',
            name='name',
        ),
        migrations.AddField(
            model_name='business',
            name='billing_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly (Save up to 20%)')], default='monthly', help_text='Billing frequency for this business (monthly or yearly)', max_length=10),
        ),
        migrations.AddField(
            model_name='pricingtier',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('supporter', 'Supporter'), ('featured', 'Featured')], default='free', help_text='Tier type (free, supporter, featured)', max_length=20),
        ),
    ]
