# Generated by Django 5.2.4 on 2025-08-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_wheelerverification_selfie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='mobility_mapper_business_portal/business_logos/'),
        ),
        migrations.AlterField(
            model_name='wheelerverification',
            name='selfie',
            field=models.ImageField(blank=True, help_text='A selfie of the Wheeler taken at the business.', max_length=255, null=True, upload_to='mobility_mapper_business_portal/wheeler_selfies/'),
        ),
        migrations.AlterField(
            model_name='wheelerverificationphoto',
            name='image',
            field=models.ImageField(max_length=255, upload_to='mobility_mapper_business_portal/verification_photos/'),
        ),
    ]
