# Generated by Django 5.2.4 on 2025-07-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_business_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='owner',
            new_name='business_owner',
        ),
        migrations.RenameField(
            model_name='pricingtier',
            old_name='stripe_price_id',
            new_name='stripe_monthly_price_id',
        ),
        migrations.RemoveField(
            model_name='business',
            name='category',
        ),
        migrations.AddField(
            model_name='business',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number for the business', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='facebook',
            field=models.URLField(blank=True, help_text='Facebook page URL', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='instagram',
            field=models.URLField(blank=True, help_text='Instagram profile URL', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='opening_hours',
            field=models.TextField(blank=True, help_text='Opening hours in text format', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='public_email',
            field=models.EmailField(blank=True, help_text='Public email address for the business', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='public_phone',
            field=models.CharField(blank=True, help_text='Public phone number for the business', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='services_offered',
            field=models.TextField(blank=True, help_text='Services offered by the business', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='special_offers',
            field=models.TextField(blank=True, help_text='Special offers or discounts available for wheelers', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True, help_text='Website URL for the business', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='x_twitter',
            field=models.URLField(blank=True, help_text='X profile URL', null=True),
        ),
        migrations.RemoveField(
            model_name='business',
            name='accessibility_features',
        ),
        migrations.AddField(
            model_name='business',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='businesses', to='businesses.category'),
        ),
        migrations.AddField(
            model_name='business',
            name='accessibility_features',
            field=models.ManyToManyField(blank=True, related_name='businesses', to='businesses.accessibilityfeature'),
        ),
    ]
