# Generated by Django 5.2.4 on 2025-07-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0010_accessibilityfeature_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='group_code',
            field=models.CharField(blank=True, help_text="Group code for category grouping (e.g. 'retail', 'food_drink')", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='group_description',
            field=models.CharField(blank=True, help_text="Description of the group (e.g. 'Retail', 'Food & Drink')", max_length=200, null=True),
        ),
    ]
