# Generated by Django 5.2.4 on 2025-07-21 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0011_category_group_code_category_group_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='facebook',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='instagram',
            new_name='instagram_url',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='x_twitter',
            new_name='x_twitter_url',
        ),
    ]
