# Generated by Django 5.2.4 on 2025-07-24 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0012_rename_facebook_business_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelerVerificationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='verification_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='businesses.wheelerverification')),
            ],
        ),
    ]
