# Generated by Django 5.2.4 on 2025-07-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0013_wheelerverificationphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelerverification',
            name='mobility_device',
            field=models.CharField(blank=True, choices=[('manual_wheelchair', 'Manual Wheelchair'), ('powered_wheelchair', 'Powered Wheelchair'), ('manual_wheelchair_with_powered_front_attachment', 'Manual Wheelchair with Powered Front Attachment'), ('all_terrain_wheelchair', 'All Terrain Wheelchair'), ('mobility_scooter_class_2', 'Mobility Scooter Class 2 (for footpaths)'), ('mobility_scooter_class_3', 'Mobility Scooter Class 3 (for road use)'), ('tricycle', 'Tricycle'), ('handcycle', 'Handcycle'), ('adapted_bicycle', 'Adapted Bicycle'), ('bicycle', 'Bicycle'), ('other', 'Other')], help_text='Type of wheeled mobility device used during verification.', max_length=47, null=True),
        ),
    ]
