# Generated by Django 5.2.4 on 2025-07-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0015_wheelerverificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelerverification',
            name='approved',
            field=models.BooleanField(default=False, help_text='Has this verification been approved by an admin?'),
        ),
    ]
