# Generated by Django 5.2.4 on 2025-07-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0016_wheelerverification_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='opening_hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='public_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='public_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='services_offered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
