# Generated by Django 5.2.4 on 2025-08-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0017_alter_business_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='accessibilityfeature',
            name='code',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='accessibilityfeature',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
