# Generated by Django 5.2.4 on 2025-08-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0018_category_tags_alter_accessibilityfeature_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
