# Generated by Django 5.2.4 on 2025-08-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0019_alter_category_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelerverificationrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
