# Generated by Django 5.2.4 on 2025-08-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0020_wheelerverificationrequest_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelerverification',
            name='additional_features',
            field=models.ManyToManyField(blank=True, related_name='additional_in_verifications', to='businesses.accessibilityfeature'),
        ),
        migrations.AddField(
            model_name='wheelerverification',
            name='confirmed_features',
            field=models.ManyToManyField(related_name='confirmed_in_verifications', to='businesses.accessibilityfeature'),
        ),
    ]
