# Generated by Django 5.2.4 on 2025-08-09 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0021_wheelerverification_additional_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelerverificationphoto',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_photos', to='businesses.accessibilityfeature'),
        ),
    ]
