# Generated by Django 5.2.4 on 2025-08-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0022_wheelerverificationphoto_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheelerverification',
            name='comments',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
    ]
