# Generated by Django 5.2.4 on 2025-08-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0023_alter_wheelerverification_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingtier',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium')], default='free', help_text='Tier type (free, supporter, featured)', max_length=20),
        ),
    ]
