# Generated by Django 5.2.4 on 2025-08-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0024_alter_pricingtier_tier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/business_logos/'),
        ),
        migrations.AlterField(
            model_name='wheelerverificationphoto',
            name='image',
            field=models.ImageField(upload_to='media/verification_photos/'),
        ),
    ]
