# Generated by Django 5.2.4 on 2025-08-15 00:07

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0025_alter_business_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='media/business_logos/'),
        ),
        migrations.AlterField(
            model_name='wheelerverificationphoto',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='media/verification_photos/'),
        ),
    ]
