# Generated by Django 5.2.4 on 2025-09-06 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobilityDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('UK', 'United Kingdom'), ('Other', 'Other')], default='UK', help_text='Country of residence.', max_length=32)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='mobility_mapper_business_portal/profile_photos/')),
                ('is_wheeler', models.BooleanField(default=False)),
                ('has_business', models.BooleanField(default=False)),
                ('has_registered_business', models.BooleanField(default=False, help_text='Whether the user has registered their business on the site.')),
                ('mobility_devices_other', models.CharField(blank=True, help_text="Other mobility device description (if 'Other' selected).", max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.agegroup')),
                ('county', models.ForeignKey(blank=True, help_text='County of residence', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.county')),
                ('mobility_devices', models.ManyToManyField(blank=True, help_text='Types of wheeled mobility devices (if user is a wheeler).', to='accounts.mobilitydevice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
