# Generated by Django 5.2.4 on 2025-08-18 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('UK', 'United Kingdom'), ('Other', 'Other')], default='UK', help_text='Country of residence.', max_length=32)),
                ('county', models.CharField(blank=True, choices=[('Bedfordshire', 'Bedfordshire'), ('Berkshire', 'Berkshire'), ('Bristol', 'Bristol'), ('Buckinghamshire', 'Buckinghamshire'), ('Cambridgeshire', 'Cambridgeshire'), ('Cheshire', 'Cheshire'), ('City of London', 'City of London'), ('Cornwall', 'Cornwall'), ('Cumbria', 'Cumbria'), ('Derbyshire', 'Derbyshire'), ('Devon', 'Devon'), ('Dorset', 'Dorset'), ('Durham', 'Durham'), ('East Riding of Yorkshire', 'East Riding of Yorkshire'), ('East Sussex', 'East Sussex'), ('Essex', 'Essex'), ('Gloucestershire', 'Gloucestershire'), ('Greater London', 'Greater London'), ('Greater Manchester', 'Greater Manchester'), ('Hampshire', 'Hampshire'), ('Herefordshire', 'Herefordshire'), ('Hertfordshire', 'Hertfordshire'), ('Isle of Wight', 'Isle of Wight'), ('Kent', 'Kent'), ('Lancashire', 'Lancashire'), ('Leicestershire', 'Leicestershire'), ('Lincolnshire', 'Lincolnshire'), ('Merseyside', 'Merseyside'), ('Norfolk', 'Norfolk'), ('North Yorkshire', 'North Yorkshire'), ('Northamptonshire', 'Northamptonshire'), ('Northumberland', 'Northumberland'), ('Nottinghamshire', 'Nottinghamshire'), ('Oxfordshire', 'Oxfordshire'), ('Rutland', 'Rutland'), ('Shropshire', 'Shropshire'), ('Somerset', 'Somerset'), ('South Yorkshire', 'South Yorkshire'), ('Staffordshire', 'Staffordshire'), ('Suffolk', 'Suffolk'), ('Surrey', 'Surrey'), ('Tyne and Wear', 'Tyne and Wear'), ('Warwickshire', 'Warwickshire'), ('West Midlands', 'West Midlands'), ('West Sussex', 'West Sussex'), ('West Yorkshire', 'West Yorkshire'), ('Wiltshire', 'Wiltshire'), ('Worcestershire', 'Worcestershire'), ('Anglesey', 'Anglesey'), ('Brecknockshire', 'Brecknockshire'), ('Caernarfonshire', 'Caernarfonshire'), ('Cardiganshire', 'Cardiganshire'), ('Carmarthenshire', 'Carmarthenshire'), ('Clwyd', 'Clwyd'), ('Denbighshire', 'Denbighshire'), ('Flintshire', 'Flintshire'), ('Glamorgan', 'Glamorgan'), ('Merionethshire', 'Merionethshire'), ('Monmouthshire', 'Monmouthshire'), ('Montgomeryshire', 'Montgomeryshire'), ('Pembrokeshire', 'Pembrokeshire'), ('Powys', 'Powys'), ('Radnorshire', 'Radnorshire'), ('Swansea', 'Swansea'), ('Wrexham', 'Wrexham'), ('Aberdeen City', 'Aberdeen City'), ('Aberdeenshire', 'Aberdeenshire'), ('Angus', 'Angus'), ('Argyll and Bute', 'Argyll and Bute'), ('Clackmannanshire', 'Clackmannanshire'), ('Dumfries and Galloway', 'Dumfries and Galloway'), ('Dundee City', 'Dundee City'), ('East Ayrshire', 'East Ayrshire'), ('East Dunbartonshire', 'East Dunbartonshire'), ('East Lothian', 'East Lothian'), ('East Renfrewshire', 'East Renfrewshire'), ('Edinburgh', 'Edinburgh'), ('Falkirk', 'Falkirk'), ('Fife', 'Fife'), ('Glasgow City', 'Glasgow City'), ('Highland', 'Highland'), ('Inverclyde', 'Inverclyde'), ('Midlothian', 'Midlothian'), ('Moray', 'Moray'), ('North Ayrshire', 'North Ayrshire'), ('North Lanarkshire', 'North Lanarkshire'), ('Orkney Islands', 'Orkney Islands'), ('Perth and Kinross', 'Perth and Kinross'), ('Renfrewshire', 'Renfrewshire'), ('Scottish Borders', 'Scottish Borders'), ('Shetland Islands', 'Shetland Islands'), ('South Ayrshire', 'South Ayrshire'), ('South Lanarkshire', 'South Lanarkshire'), ('Stirling', 'Stirling'), ('West Dunbartonshire', 'West Dunbartonshire'), ('West Lothian', 'West Lothian'), ('Western Isles', 'Western Isles')], help_text='County of residence', max_length=64, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('is_wheeler', models.BooleanField(default=False)),
                ('has_business', models.BooleanField(default=False)),
                ('has_registered_business', models.BooleanField(default=False, help_text='Whether the user has registered their business on the site.')),
                ('mobility_devices', models.JSONField(blank=True, default=list, help_text='Types of wheeled mobility devices (if user is a wheeler).')),
                ('mobility_devices_other', models.CharField(blank=True, help_text="Other mobility device description (if 'Other' selected).", max_length=100, null=True)),
                ('age_group', models.CharField(blank=True, choices=[('under_18', 'Under 18'), ('18_24', '18-24'), ('25_34', '25-34'), ('35_44', '35-44'), ('45_54', '45-54'), ('55_64', '55-64'), ('65_plus', '65+')], help_text="User's age group.", max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
