# Generated by Django 5.2.4 on 2025-07-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_wheeler',
            field=models.BooleanField(default=False),
        ),
    ]
