# Generated by Django 5.2.4 on 2025-09-19 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age_group',
            field=models.ForeignKey(blank=True, help_text='Age group of the user.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.agegroup'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='county',
            field=models.ForeignKey(blank=True, help_text='County of residence.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.county'),
        ),
    ]
