# Generated by Django 5.2.4 on 2025-08-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age_group',
            field=models.CharField(blank=True, choices=[('under_18', 'Under 18'), ('18_24', '18-24'), ('25_34', '25-34'), ('35_44', '35-44'), ('45_54', '45-54'), ('55_64', '55-64'), ('65_plus', '65+')], max_length=16, null=True),
        ),
    ]
