# Generated by Django 5.2.4 on 2025-07-19 22:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_is_wheeler'),
        ('businesses', '0004_alter_business_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age_group',
            field=models.CharField(blank=True, choices=[('under_18', 'Under 18'), ('18_24', '18-24'), ('25_34', '25-34'), ('35_44', '35-44'), ('45_54', '45-54'), ('55_64', '55-64'), ('65_plus', '65+')], help_text="User's age group.", max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Business owned by the user (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(choices=[('UK', 'United Kingdom'), ('Other', 'Other')], default='UK', help_text='Country of residence.', max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='county',
            field=models.CharField(blank=True, choices=[('Bedfordshire', 'Bedfordshire'), ('Berkshire', 'Berkshire'), ('Bristol', 'Bristol'), ('Buckinghamshire', 'Buckinghamshire'), ('Cambridgeshire', 'Cambridgeshire'), ('Cheshire', 'Cheshire'), ('City of London', 'City of London'), ('Cornwall', 'Cornwall'), ('Cumbria', 'Cumbria'), ('Derbyshire', 'Derbyshire'), ('Devon', 'Devon'), ('Dorset', 'Dorset'), ('Durham', 'Durham'), ('East Riding of Yorkshire', 'East Riding of Yorkshire'), ('East Sussex', 'East Sussex'), ('Essex', 'Essex'), ('Gloucestershire', 'Gloucestershire'), ('Greater London', 'Greater London'), ('Greater Manchester', 'Greater Manchester'), ('Hampshire', 'Hampshire'), ('Herefordshire', 'Herefordshire'), ('Hertfordshire', 'Hertfordshire'), ('Isle of Wight', 'Isle of Wight'), ('Kent', 'Kent'), ('Lancashire', 'Lancashire'), ('Leicestershire', 'Leicestershire'), ('Lincolnshire', 'Lincolnshire'), ('Merseyside', 'Merseyside'), ('Norfolk', 'Norfolk'), ('North Yorkshire', 'North Yorkshire'), ('Northamptonshire', 'Northamptonshire'), ('Northumberland', 'Northumberland'), ('Nottinghamshire', 'Nottinghamshire'), ('Oxfordshire', 'Oxfordshire'), ('Rutland', 'Rutland'), ('Shropshire', 'Shropshire'), ('Somerset', 'Somerset'), ('South Yorkshire', 'South Yorkshire'), ('Staffordshire', 'Staffordshire'), ('Suffolk', 'Suffolk'), ('Surrey', 'Surrey'), ('Tyne and Wear', 'Tyne and Wear'), ('Warwickshire', 'Warwickshire'), ('West Midlands', 'West Midlands'), ('West Sussex', 'West Sussex'), ('West Yorkshire', 'West Yorkshire'), ('Wiltshire', 'Wiltshire'), ('Worcestershire', 'Worcestershire')], help_text='UK county (if country is UK). Leave blank if not applicable.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobility_device',
            field=models.CharField(blank=True, choices=[('manual_wheelchair', 'Manual Wheelchair'), ('powered_wheelchair', 'Powered Wheelchair'), ('manual_wheelchair_with_powered_front_attachment', 'Manual Wheelchair with Powered Front Attachment'), ('all_terrain_wheelchair', 'All Terrain Wheelchair'), ('mobility_scooter_class_2', 'Mobility Scooter Class 2 (for footpaths)'), ('mobility_scooter_class_3', 'Mobility Scooter Class 3 (for road use)'), ('tricycle', 'Tricycle'), ('handcycle', 'Handcycle'), ('adapted_bicycle', 'Adapted Bicycle'), ('bicycle', 'Bicycle'), ('other', 'Other')], help_text='Type of wheeled mobility device (if user is a wheeler).', max_length=47, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
