# Generated by Django 5.2.4 on 2025-08-28 23:19

import django.db.models.deletion
from django.db import migrations, models
import django.db.models.deletion

def populate_age_groups(apps, schema_editor):
    AgeGroup = apps.get_model('accounts', 'AgeGroup')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    AGE_CHOICES = [
        ('under_18', 'Under 18'),
        ('18_24', '18-24'),
        ('25_34', '25-34'),
        ('35_44', '35-44'),
        ('45_54', '45-54'),
        ('55_64', '55-64'),
        ('65_plus', '65+'),
    ]
    # Create all AgeGroup entries
    for code, desc in AGE_CHOICES:
        AgeGroup.objects.get_or_create(code=code, defaults={'description': desc})
    # Migrate existing UserProfile.age_group strings to FK
    for up in UserProfile.objects.all():
        old_code = getattr(up, 'age_group', None)
        if old_code:
            ag = AgeGroup.objects.filter(code=old_code).first()
            if ag:
                up.age_group = ag
                up.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_age_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobilityDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    migrations.RunPython(populate_age_groups, migrations.RunPython.noop),
    migrations.RemoveField(
            model_name='userprofile',
            name='mobility_devices',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.agegroup'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='county',
            field=models.ForeignKey(blank=True, help_text='County of residence', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.county'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobility_devices',
            field=models.ManyToManyField(blank=True, help_text='Types of wheeled mobility devices (if user is a wheeler).', to='accounts.mobilitydevice'),
        ),
    ]
