# Generated by Django 5.2.4 on 2025-08-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userprofile_hide_results_tip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mobility_device',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobility_devices',
            field=models.JSONField(blank=True, default=list, help_text='Types of wheeled mobility devices (if user is a wheeler).'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobility_devices_other',
            field=models.CharField(blank=True, help_text="Other mobility device description (if 'Other' selected).", max_length=100, null=True),
        ),
    ]
