# Generated by Django 5.2.4 on 2025-08-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(default='Pembrokeshire', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(default='SA32 6HD', max_length=20),
            preserve_default=False,
        ),
    ]
