# Generated by Django 5.2.4 on 2025-09-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_purchase_delete_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='total_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='selected_tier',
            new_name='membership_tier',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_type',
            field=models.CharField(choices=[('membership', 'Membership for one year'), ('verification', 'Verification of Accessibility Features')], max_length=20),
        ),
    ]
