# Generated by Django 5.2.4 on 2025-08-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_order_county_alter_order_postcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_subscription_id',
        ),
    ]
