# Generated by Django 5.2.4 on 2025-08-28 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_remove_order_stripe_subscription_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tier',
            new_name='selected_tier',
        ),
    ]
