# Generated by Django 5.2.4 on 2025-09-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_checkoutcache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='membership_stripe_price_id',
        ),
    ]
