# Generated by Django 5.2.4 on 2025-08-28 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_alter_pricingtier_description_and_more'),
        ('checkout', '0005_rename_tier_order_selected_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='interval',
        ),
        migrations.AlterField(
            model_name='order',
            name='selected_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.pricingtier'),
        ),
    ]
