# Generated by Django 5.2.4 on 2025-09-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_remove_purchase_membership_stripe_price_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutcache',
            name='payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
